/**
 * mock-data.ts — Offline fallback when the API is unavailable.
 * Cover seeds align with `DatabaseSeeder` (Laravel) for a consistent demo.
 */

import type { BookCardData } from "@/components/books/book-card"
import { demoPic } from "@/lib/demo-images"

export const MOCK_BOOKS: BookCardData[] = [
  {
    id: "bk_001",
    title: "The Lagos Chronicles",
    author: "Chimamanda A.",
    coverUrl: demoPic("core-bk-lagos"),
    rating: 4.8,
    reviewCount: 1240,
    accessType: "SUBSCRIPTION",
    format: "ebook",
    category: "Fiction",
    isTrending: true,
    isNew: false,
  },
  {
    id: "bk_002",
    title: "Atomic Habits: African Edition",
    author: "James Okafor",
    coverUrl: demoPic("core-bk-atomic"),
    rating: 4.9,
    reviewCount: 3400,
    price: 12.99,
    currency: "$",
    accessType: "PAID",
    format: "ebook",
    category: "Self-Help",
    isTrending: true,
    isNew: true,
  },
  {
    id: "bk_003",
    title: "Voices from the Savanna",
    author: "Wanjiru Mwangi",
    coverUrl: demoPic("core-bk-savanna"),
    rating: 4.6,
    reviewCount: 780,
    accessType: "FREE",
    format: "ebook",
    category: "Poetry",
    isNew: true,
  },
  {
    id: "bk_004",
    title: "The Entrepreneur's Code",
    author: "Tunde Balogun",
    coverUrl: demoPic("core-bk-entrepreneur"),
    rating: 4.7,
    reviewCount: 2100,
    accessType: "SUBSCRIPTION",
    format: "ebook",
    category: "Business",
    isTrending: true,
  },
  {
    id: "bk_005",
    title: "Midnight in Accra",
    author: "Efua Asante",
    coverUrl: demoPic("core-bk-accra"),
    rating: 4.5,
    reviewCount: 920,
    price: 8.99,
    currency: "$",
    accessType: "PAID",
    format: "ebook",
    category: "Romance",
  },
  {
    id: "bk_006",
    title: "Tech Giants of Africa",
    author: "Seun Adesanya",
    coverUrl: demoPic("core-bk-tech-giants"),
    rating: 4.4,
    reviewCount: 560,
    accessType: "SUBSCRIPTION",
    format: "ebook",
    category: "Technology",
    isNew: true,
  },
  {
    id: "bk_007",
    title: "The Baobab Tree",
    author: "Ngozi Adeyemi",
    coverUrl: demoPic("core-bk-baobab"),
    rating: 4.8,
    reviewCount: 1560,
    accessType: "FREE",
    format: "ebook",
    category: "Children",
  },
  {
    id: "bk_008",
    title: "Currency of Knowledge",
    author: "Dr. Amaka Eze",
    coverUrl: demoPic("core-bk-currency"),
    rating: 4.3,
    reviewCount: 340,
    price: 19.99,
    currency: "$",
    accessType: "PAID",
    format: "audiobook",
    category: "Finance",
  },
  {
    id: "bk_009",
    title: "Sacred Grounds",
    author: "Bisi Ogunwale",
    coverUrl: demoPic("core-bk-sacred"),
    rating: 4.6,
    reviewCount: 890,
    accessType: "SUBSCRIPTION",
    format: "ebook",
    category: "Historical",
    isTrending: true,
  },
  {
    id: "bk_010",
    title: "Python for Data Scientists",
    author: "Kofi Mensah",
    coverUrl: demoPic("core-bk-python"),
    rating: 4.7,
    reviewCount: 2800,
    price: 24.99,
    currency: "$",
    accessType: "PAID",
    format: "ebook",
    category: "Technology",
    isNew: true,
  },
  {
    id: "bk_011",
    title: "The River Between Us",
    author: "Amina Diallo",
    coverUrl: demoPic("core-bk-river"),
    rating: 4.5,
    reviewCount: 670,
    accessType: "SUBSCRIPTION",
    format: "audiobook",
    category: "Fiction",
  },
  {
    id: "bk_012",
    title: "Leadership in Crisis",
    author: "Gen. Emeka Nwosu",
    coverUrl: demoPic("core-bk-leadership"),
    rating: 4.8,
    reviewCount: 1100,
    accessType: "SUBSCRIPTION",
    format: "ebook",
    category: "Leadership",
    isTrending: true,
  },
  {
    id: "bk_013",
    title: "Copper Sun Rising",
    author: "Chimamanda A.",
    coverUrl: demoPic("core-bk-013-copper"),
    rating: 4.6,
    reviewCount: 1840,
    accessType: "SUBSCRIPTION",
    format: "ebook",
    category: "Fiction",
    isTrending: true,
  },
  {
    id: "bk_014",
    title: "The Taxman's Daughter",
    author: "Dr. Amaka Eze",
    coverUrl: demoPic("core-bk-014-taxman"),
    rating: 4.4,
    reviewCount: 412,
    price: 11.99,
    currency: "$",
    accessType: "PAID",
    format: "ebook",
    category: "Finance",
  },
  {
    id: "bk_015",
    title: "Selma Street Blues",
    author: "James Okafor",
    coverUrl: demoPic("core-bk-015-selma"),
    rating: 4.5,
    reviewCount: 228,
    price: 10.49,
    currency: "$",
    accessType: "PAID",
    format: "ebook",
    category: "Fiction",
    isNew: true,
  },
  {
    id: "bk_016",
    title: "Docker on a Budget",
    author: "Kofi Mensah",
    coverUrl: demoPic("core-bk-016-docker"),
    rating: 4.7,
    reviewCount: 1520,
    price: 15.99,
    currency: "$",
    accessType: "PAID",
    format: "ebook",
    category: "Technology",
    isNew: true,
    isTrending: true,
  },
  {
    id: "bk_017",
    title: "Morning Meditations",
    author: "Wanjiru Mwangi",
    coverUrl: demoPic("core-bk-017-morning"),
    rating: 4.5,
    reviewCount: 5600,
    accessType: "FREE",
    format: "ebook",
    category: "Self-Help",
  },
  {
    id: "bk_018",
    title: "Queen of the Terrace",
    author: "Efua Asante",
    coverUrl: demoPic("core-bk-018-terrace"),
    rating: 4.3,
    reviewCount: 990,
    accessType: "SUBSCRIPTION",
    format: "ebook",
    category: "Romance",
    isTrending: true,
  },
  {
    id: "bk_019",
    title: "Little Giants",
    author: "Ngozi Adeyemi",
    coverUrl: demoPic("core-bk-019-giants"),
    rating: 4.9,
    reviewCount: 2100,
    accessType: "FREE",
    format: "ebook",
    category: "Children",
  },
  {
    id: "bk_020",
    title: "Grain Routes",
    author: "Bisi Ogunwale",
    coverUrl: demoPic("core-bk-020-grain"),
    rating: 4.6,
    reviewCount: 743,
    price: 13.99,
    currency: "$",
    accessType: "PAID",
    format: "ebook",
    category: "Historical",
  },
  {
    id: "bk_021",
    title: "The VC Playbook",
    author: "Tunde Balogun",
    coverUrl: demoPic("core-bk-021-vc"),
    rating: 4.8,
    reviewCount: 3100,
    accessType: "SUBSCRIPTION",
    format: "ebook",
    category: "Business",
    isTrending: true,
  },
  {
    id: "bk_022",
    title: "Nights in Dakar",
    author: "Amina Diallo",
    coverUrl: demoPic("core-bk-022-dakar"),
    rating: 4.6,
    reviewCount: 445,
    price: 9.49,
    currency: "$",
    accessType: "PAID",
    format: "audiobook",
    category: "Romance",
  },
  {
    id: "bk_023",
    title: "Ansible for Humans",
    author: "Seun Adesanya",
    coverUrl: demoPic("core-bk-023-ansible"),
    rating: 4.5,
    reviewCount: 880,
    price: 21.99,
    currency: "$",
    accessType: "PAID",
    format: "ebook",
    category: "Technology",
  },
  {
    id: "bk_024",
    title: "Rhymes for Rainy Days",
    author: "Wanjiru Mwangi",
    coverUrl: demoPic("core-bk-024-rhymes"),
    rating: 4.7,
    reviewCount: 1200,
    accessType: "FREE",
    format: "ebook",
    category: "Poetry",
  },
  {
    id: "bk_025",
    title: "Board Exam Survival",
    author: "James Okafor",
    coverUrl: demoPic("core-bk-025-board"),
    rating: 4.4,
    reviewCount: 3200,
    price: 6.99,
    currency: "$",
    accessType: "PAID",
    format: "ebook",
    category: "Self-Help",
    isNew: true,
  },
  {
    id: "bk_026",
    title: "The Copper Mine",
    author: "Gen. Emeka Nwosu",
    coverUrl: demoPic("core-bk-026-mine"),
    rating: 4.5,
    reviewCount: 670,
    accessType: "SUBSCRIPTION",
    format: "ebook",
    category: "Historical",
  },
  {
    id: "bk_027",
    title: "African SF Anthology Vol. 1",
    author: "Chimamanda A.",
    coverUrl: demoPic("core-bk-027-sf-anth"),
    rating: 4.8,
    reviewCount: 1890,
    price: 16.99,
    currency: "$",
    accessType: "PAID",
    format: "ebook",
    category: "Sci-Fi",
    isNew: true,
    isTrending: true,
  },
  {
    id: "bk_028",
    title: "Smoothie Science",
    author: "Efua Asante",
    coverUrl: demoPic("core-bk-028-smoothie"),
    rating: 4.2,
    reviewCount: 2100,
    price: 8.99,
    currency: "$",
    accessType: "PAID",
    format: "ebook",
    category: "Lifestyle",
  },
  {
    id: "bk_029",
    title: "Podcasting Gold",
    author: "Tunde Balogun",
    coverUrl: demoPic("core-bk-029-podcast"),
    rating: 4.6,
    reviewCount: 540,
    price: 14.99,
    currency: "$",
    accessType: "PAID",
    format: "ebook",
    category: "Business",
  },
  {
    id: "bk_030",
    title: "Kente & Algorithms",
    author: "Kofi Mensah",
    coverUrl: demoPic("core-bk-030-kente"),
    rating: 4.7,
    reviewCount: 920,
    accessType: "SUBSCRIPTION",
    format: "ebook",
    category: "Technology",
  },
  {
    id: "bk_031",
    title: "The Orphan Express",
    author: "Ngozi Adeyemi",
    coverUrl: demoPic("core-bk-031-orphan"),
    rating: 4.8,
    reviewCount: 760,
    price: 5.99,
    currency: "$",
    accessType: "PAID",
    format: "ebook",
    category: "Children",
  },
  {
    id: "bk_032",
    title: "War Room Ethics",
    author: "Gen. Emeka Nwosu",
    coverUrl: demoPic("core-bk-032-warroom"),
    rating: 4.5,
    reviewCount: 430,
    accessType: "SUBSCRIPTION",
    format: "audiobook",
    category: "Leadership",
  },
  {
    id: "bk_033",
    title: "Coffee Table Africa",
    author: "Amina Diallo",
    coverUrl: demoPic("core-bk-033-mag"),
    rating: 4.6,
    reviewCount: 890,
    price: 4.99,
    currency: "$",
    accessType: "PAID",
    format: "magazine",
    category: "Magazine",
    isNew: true,
  },
  {
    id: "bk_034",
    title: "Listening to Lagos",
    author: "Chimamanda A.",
    coverUrl: demoPic("core-bk-034-lagos-audio"),
    rating: 4.9,
    reviewCount: 2400,
    accessType: "SUBSCRIPTION",
    format: "audiobook",
    category: "Fiction",
    isTrending: true,
  },
  {
    id: "bk_035",
    title: "Garden State Mind",
    author: "Dr. Amaka Eze",
    coverUrl: demoPic("core-bk-035-garden"),
    rating: 4.4,
    reviewCount: 1100,
    accessType: "SUBSCRIPTION",
    format: "ebook",
    category: "Self-Help",
  },
  {
    id: "bk_036",
    title: "Eclipse over Addis",
    author: "Seun Adesanya",
    coverUrl: demoPic("core-bk-036-eclipse"),
    rating: 4.7,
    reviewCount: 1450,
    price: 12.49,
    currency: "$",
    accessType: "PAID",
    format: "ebook",
    category: "Sci-Fi",
    isTrending: true,
  },
]

export const CATEGORIES = [
  { id: "cat_fiction",  label: "Fiction",    icon: "BookOpen",    count: 28420, color: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400" },
  { id: "cat_selfhelp", label: "Self-Help",  icon: "Zap",         count: 15340, color: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400" },
  { id: "cat_business", label: "Business",   icon: "Briefcase",   count: 11200, color: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400" },
  { id: "cat_romance",  label: "Romance",    icon: "Heart",       count: 19870, color: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400" },
  { id: "cat_tech",     label: "Technology", icon: "Monitor",     count: 14500, color: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-400" },
  { id: "cat_history",  label: "Historical", icon: "Landmark",    count: 8200,  color: "bg-stone-100 text-stone-700 dark:bg-stone-900/30 dark:text-stone-400" },
  { id: "cat_poetry",   label: "Poetry",     icon: "PenLine",     count: 6100,  color: "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400" },
  { id: "cat_children", label: "Children",   icon: "Smile",       count: 9600,  color: "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400" },
  { id: "cat_lead",     label: "Leadership", icon: "Briefcase",   count: 4800,  color: "bg-slate-100 text-slate-700 dark:bg-slate-900/30 dark:text-slate-400" },
  { id: "cat_finance",  label: "Finance",    icon: "Briefcase",   count: 6400,  color: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400" },
  { id: "cat_scifi",    label: "Sci-Fi",     icon: "Monitor",     count: 7200,  color: "bg-cyan-100 text-cyan-800 dark:bg-cyan-900/30 dark:text-cyan-300" },
  { id: "cat_life",     label: "Lifestyle",  icon: "Heart",       count: 5100,  color: "bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-400" },
  { id: "cat_mag",      label: "Magazine",   icon: "BookOpen",    count: 3200,  color: "bg-orange-100 text-orange-800 dark:bg-orange-900/30 dark:text-orange-300" },
]

export const SUBSCRIPTION_PLANS = [
  {
    id: "plan_monthly",
    name: "Pro Monthly",
    price: 9.99,
    currency: "$",
    duration: 30,
    label: "Monthly",
    features: [
      "Unlimited book access",
      "Audiobook streaming",
      "Reading progress sync",
      "Offline downloads (5 books)",
      "Priority customer support",
    ],
    isPopular: false,
  },
  {
    id: "plan_yearly",
    name: "Pro Annual",
    price: 79.99,
    currency: "$",
    duration: 365,
    label: "Yearly",
    savings: "Save 33%",
    features: [
      "Everything in Monthly",
      "Unlimited offline downloads",
      "Early access to new releases",
      "Author livestream access",
      "Ad-free experience",
    ],
    isPopular: true,
  },
]

export const HERO_BANNERS = [
  {
    id: "banner_001",
    title: "Discover Africa's Best Stories",
    subtitle: "Over 50,000 ebooks, audiobooks & magazines from talented authors across Africa and the world.",
    cta: "Start Reading Free",
    ctaHref: "/auth/register?next=%2Fbooks",
    secondaryCta: "Browse Library",
    secondaryCtaHref: "/books",
    badge: "Limited Offer",
    badgeText: "First month free",
    image: demoPic("mock-hero-reading", 800, 500),
    theme: "amber",
  },
  {
    id: "banner_002",
    title: "Unlimited Reading. One Price.",
    subtitle: "Subscribe and access thousands of subscription books instantly. Read anywhere, anytime.",
    cta: "View Plans",
    ctaHref: "/subscription",
    badge: "Pro Annual",
    badgeText: "Save 33%",
    image: demoPic("mock-hero-subscribe", 800, 500),
    theme: "sky",
  },
]

export const TRENDING_AUTHORS = [
  { id: "auth_001", name: "Chimamanda A.", books: 12, followers: 45200, avatar: demoPic("mock-author-1", 80, 80) },
  { id: "auth_002", name: "Tunde Balogun", books: 8, followers: 28300, avatar: demoPic("mock-author-2", 80, 80) },
  { id: "auth_003", name: "Wanjiru Mwangi", books: 15, followers: 61000, avatar: demoPic("mock-author-3", 80, 80) },
  { id: "auth_004", name: "Seun Adesanya", books: 6, followers: 18700, avatar: demoPic("mock-author-4", 80, 80) },
]

export type MockAuthorRef = { id: string; name: string }

/** Trending + authors directory ids; names must match `MOCK_BOOKS[].author` where books exist. */
const MOCK_AUTHOR_ID_TO_NAME: Record<string, string> = {
  ...Object.fromEntries(TRENDING_AUTHORS.map(a => [a.id, a.name] as [string, string])),
  auth_005: "Ngozi Adeyemi",
  auth_006: "Kofi Mensah",
  auth_007: "Amina Diallo",
  auth_008: "Seun Williams",
  auth_009: "Dr. Amaka Eze",
  auth_010: "Gen. Emeka Nwosu",
  auth_011: "Efua Asante",
  auth_012: "Bisi Ogunwale",
}

/** Map mock author ids (e.g. auth_001) to catalog display names for /books?author_id= */
export function resolveMockAuthorId(authorId: string): MockAuthorRef | null {
  const name = MOCK_AUTHOR_ID_TO_NAME[authorId]
  return name !== undefined ? { id: authorId, name } : null
}
